### ISSUE TITLE
How did you generate the languages picture?

### ISSUE THREAD

**Issue by kaarthiksundar** [opensorceror/Data-Engineer-Resume-LaTeX#1]
What software was used to generate the languages doughnut chart?

**Comment by opensorceror** [comment]
@kaarthiksundar I used [Amcharts](https://www.amcharts.com/) to generate the donut chart. This is something I would really like to change, and instead generate it with LaTeX. Any suggestions / code contributions are welcome!

**Comment by HiTuX** [comment]
I think it is posssible to do it in `Tikz`. Here is [example](http://tex.stackexchange.com/questions/82727/create-a-ring-diagram-in-tex)

**Comment by opensorceror** [comment]
@HiTuX I welcome a pull request!
