### ISSUE TITLE
geting errors

### ISSUE THREAD

**Issue by pranitkaadam** [opensorceror/Data-Engineer-Resume-LaTeX#2]
![screenshot 2](https://cloud.githubusercontent.com/assets/26231961/25349097/31b535f2-293e-11e7-8c5a-9bf72da5d914.png)

**Comment by opensorceror** [comment]
Looking into it. Could you post the entire error log?

**Comment by pranitkaadam** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/26231961/25355367/fe909106-2953-11e7-8710-1d7411197359.png)


actually i copy paste the code in Miktex and getting error

**Comment by pranitkaadam** [comment]
how can  resolve this error?  i not sure what does it mean

**Comment by opensorceror** [comment]
It seems that the style file - `twentyseconds.cv` - is not present in your project directory. You'll need to fetch that file and try compiling again.
