### ISSUE TITLE
Change personal website to birthdate and "projects" to "about me"

### ISSUE THREAD

**Issue by Mataivic** [opensorceror/Data-Engineer-Resume-LaTeX#6]
Hello,

The title should be self-explanatory :).

I am currently writing my resume with your nice template but I was wondering if it was possible to : 

- Remove the "personal website" in the sidebar and put a birthdate instead (since I don't have any personal website !) ?
- Replace the "projects" section in the sidebar by another one, for instance an "about me" section or another skills overview diagram ?

Thank you.

**Comment by opensorceror** [comment]
@Mataivic Of course! Feel free to edit the `twentysecondscv.cls` file as necessary.

**Comment by Mataivic** [comment]
Ok cool ! I have never tried to modify such a file, can I have a few hints to know where to start ?

**Comment by opensorceror** [comment]
I recommend the [official LaTeX tutorial](https://www.latex-tutorial.com/). Once you get the hang of basic LaTeX concepts, you can get your hands dirty with changes to the .cls file 😃
